### ISSUE TITLE
Numerous sharing server errors

### ISSUE THREAD

**Issue by frnsys** [frnsys/half_earth#238]
Database locking

```
Traceback (most recent call last):
  File "/srv/half_earth/sharing/env/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/half_earth/sharing/env/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/half_earth/sharing/env/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/srv/half_earth/sharing/env/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/half_earth/sharing/env/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/half_earth/sharing/app.py", line 19, in index
    summary = summarize(data)
  File "/srv/half_earth/sharing/summarize.py", line 6, in summarize
    if spec['fn'](scenario):
  File "/srv/half_earth/sharing/badges.py", line 3, in <lambda>
    'fn': lambda s: any(r['seceded'] for r in s['world']['regions']),
TypeError: 'NoneType' object is not subscriptable
``

**Comment by frnsys** [comment]
Fixed by c273e54af83942d5d1b1d8aba9204c29f4bd8fdd
