### ISSUE TITLE
Screen goes black and game freezes before 2085 loading cycle

### ISSUE THREAD

**Issue by sbutler-gh** [frnsys/half_earth#245]
At the end of the 2080 planning cycle, after going through the update and making it to the results screen (e.g. showing completed projects, how many points have been awarded, etc.), when I click to **Continue** — the screen goes black and does not continue.

Here is error code:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://lmpdmoodgbbmghbdinejkabonhjbfhjk/handsfree.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://lmpdmoodgbbmghbdinejkabonhjbfhjk/chrome/lib/simple-keyboard/simple-keyboard.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
instrument.js:109 TypeError: Cannot read properties of undefined (reading 'background')
    at Proxy.u (Interstitial.vue:2:96)
    at F (runtime-core.esm-bundler.js:893:44)
    at m.fn (runtime-core.esm-bundler.js:5030:57)
    at m.run (reactivity.esm-bundler.js:167:25)
    at Y (runtime-core.esm-bundler.js:5156:9)
    at L (runtime-core.esm-bundler.js:4939:9)
    at N (runtime-core.esm-bundler.js:4897:17)
    at k (runtime-core.esm-bundler.js:4489:21)
    at O (runtime-core.esm-bundler.js:4806:13)
    at B (runtime-core.esm-bundler.js:4867:17)
    at k (runtime-core.esm-bundler.js:4482:17)
    at m.fn (runtime-core.esm-bundler.js:5107:17)
    at m.run (reactivity.esm-bundler.js:167:25)
    at s (runtime-core.esm-bundler.js:155:36)
    at S (runtime-core.esm-bundler.js:394:17)
(anonymous) @ instrument.js:109
(anonymous) @ runtime-core.esm-bundler.js:226
r @ runtime-core.esm-bundler.js:204
F @ runtime-core.esm-bundler.js:922
(anonymous) @ runtime-core.esm-bundler.js:5030
run @ reactivity.esm-bundler.js:167
Y @ runtime-core.esm-bundler.js:5156
L @ runtime-core.esm-bundler.js:4939
N @ runtime-core.esm-bundler.js:4897
k @ runtime-core.esm-bundler.js:4489
O @ runtime-core.esm-bundler.js:4806
B @ runtime-core.esm-bundler.js:4867
k @ runtime-core.esm-bundler.js:4482
(anonymous) @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
s @ runtime-core.esm-bundler.js:155
S @ runtime-core.esm-bundler.js:394
Promise.then (async)
_ @ runtime-core.esm-bundler.js:285
w @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
T @ reactivity.esm-bundler.js:359
_ @ reactivity.esm-bundler.js:332
(anonymous) @ reactivity.esm-bundler.js:484
p @ game.js:23
changePoliticalCapital @ game.js:142
nextPhase @ Report.vue:314
onClick.t.<computed>.t.<computed> @ Report.vue:125
s @ runtime-core.esm-bundler.js:155
o @ runtime-core.esm-bundler.js:164
n @ runtime-dom.esm-bundler.js:366
i @ helpers.js:73
instrument.js:109 TypeError: Cannot read properties of undefined (reading 'ambience')
    at Proxy.start (Interstitial.vue:222:88)
    at Proxy.mounted (Interstitial.vue:107:10)
    at s (runtime-core.esm-bundler.js:155:22)
    at o (runtime-core.esm-bundler.js:164:21)
    at Array.t.__weh.t.__weh (runtime-core.esm-bundler.js:2667:29)
    at P (runtime-core.esm-bundler.js:356:32)
    at S (runtime-core.esm-bundler.js:401:9)
(anonymous) @ instrument.js:109
(anonymous) @ runtime-core.esm-bundler.js:226
r @ runtime-core.esm-bundler.js:204
s @ runtime-core.esm-bundler.js:158
o @ runtime-core.esm-bundler.js:164
t.__weh.t.__weh @ runtime-core.esm-bundler.js:2667
P @ runtime-core.esm-bundler.js:356
S @ runtime-core.esm-bundler.js:401
Promise.then (async)
_ @ runtime-core.esm-bundler.js:285
w @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
T @ reactivity.esm-bundler.js:359
_ @ reactivity.esm-bundler.js:332
(anonymous) @ reactivity.esm-bundler.js:484
p @ game.js:23
changePoliticalCapital @ game.js:142
nextPhase @ Report.vue:314
onClick.t.<computed>.t.<computed> @ Report.vue:125
s @ runtime-core.esm-bundler.js:155
o @ runtime-core.esm-bundler.js:164
n @ runtime-dom.esm-bundler.js:366
i @ helpers.js:73
instrument.js:109 TypeError: Cannot read properties of undefined (reading 'background')
    at Proxy.u (Interstitial.vue:2:96)
    at F (runtime-core.esm-bundler.js:893:44)
    at m.fn (runtime-core.esm-bundler.js:5098:34)
    at m.run (reactivity.esm-bundler.js:167:25)
    at s (runtime-core.esm-bundler.js:155:36)
    at S (runtime-core.esm-bundler.js:394:17)
(anonymous) @ instrument.js:109
(anonymous) @ runtime-core.esm-bundler.js:226
r @ runtime-core.esm-bundler.js:204
F @ runtime-core.esm-bundler.js:922
(anonymous) @ runtime-core.esm-bundler.js:5098
run @ reactivity.esm-bundler.js:167
s @ runtime-core.esm-bundler.js:155
S @ runtime-core.esm-bundler.js:394
Promise.then (async)
_ @ runtime-core.esm-bundler.js:285
w @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
T @ reactivity.esm-bundler.js:359
(anonymous) @ reactivity.esm-bundler.js:965
T @ reactivity.esm-bundler.js:359
(anonymous) @ reactivity.esm-bundler.js:965
T @ reactivity.esm-bundler.js:359
_ @ reactivity.esm-bundler.js:332
(anonymous) @ reactivity.esm-bundler.js:484
p @ game.js:23
applyEvent @ game.js:181
showEvent @ EventsMixin.js:74
(anonymous) @ Interstitial.vue:217
i @ helpers.js:73
setTimeout (async)
(anonymous) @ trycatch.js:86
start @ Interstitial.vue:213
mounted @ Interstitial.vue:107
s @ runtime-core.esm-bundler.js:155
o @ runtime-core.esm-bundler.js:164
t.__weh.t.__weh @ runtime-core.esm-bundler.js:2667
P @ runtime-core.esm-bundler.js:356
S @ runtime-core.esm-bundler.js:401
Promise.then (async)
_ @ runtime-core.esm-bundler.js:285
w @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
T @ reactivity.esm-bundler.js:359
_ @ reactivity.esm-bundler.js:332
(anonymous) @ reactivity.esm-bundler.js:484
p @ game.js:23
changePoliticalCapital @ game.js:142
nextPhase @ Report.vue:314
onClick.t.<computed>.t.<computed> @ Report.vue:125
s @ runtime-core.esm-bundler.js:155
o @ runtime-core.esm-bundler.js:164
n @ runtime-dom.esm-bundler.js:366
i @ helpers.js:73
utils.js:84          POST https://o545203.ingest.sentry.io/api/6087646/envelope/?sentry_key=9c8cd525d7c64214836351b406f6e860&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
```

When I refresh and the game window reloads, and I hit continue, it returns me back to the 2080 planning screen — with all of my selections saved, ready to go ahead with the 2080 plan again.

**Comment by frnsys** [comment]
Thanks for this report! I suspect it's something to do with the fact that the game is supposed to end between 2080 and 2085, so the planning intro crashes because we're missing data for 2085. I'll have a fix for this up soon.
