### ISSUE TITLE
"capacity overflow" error (panic) when selecting more than 9 projects

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#272]
Pardon me if this is the wrong place to report this issue regarding the web version. Don't know where else I would report it otherwise. When I start a new run on play.half.earth, I tend to add a lot of the small projects in the "policies" tab. But now, when I try to go back using the "back" button, I get a sort of empty page. I narrowed it down to 9, the error happens when you add a 10th or more. In the f12 console, I get the error pasted below. Screenshot attached below. This has started happening only like this week. Using Chrome browser, but similar issue on Firefox (screenshot and error paste at the very bottom).

Chrome Version 127.0.6533.99:

```hes-game.js:642 panicked at alloc/src/raw_vec.rs:24:5:
capacity overflow

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://play.half.earth/pkg/hes-game.js:629:13)
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[6136]:0x242269
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[1451]:0x125f61
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[2974]:0x1c434c
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[4721]:0x216a62
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[2635]:0x1a90ae
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[341]:0x24a77
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[3052]:0x1c9e90
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[1585]:0x13268d


imports.wbg.__wbg_error_f851667af71bcfc6 @ hes-game.js:642
$func6136 @ hes-game.wasm:0x242339
$func1451 @ hes-game.wasm:0x125f61
$func2974 @ hes-game.wasm:0x1c434c
$func4721 @ hes-game.wasm:0x216a62
$func2635 @ hes-game.wasm:0x1a90ae
$func341 @ hes-game.wasm:0x24a77
$func367 @ hes-game.wasm:0x3a471
$func3052 @ hes-game.wasm:0x1c9e90
$func1585 @ hes-game.wasm:0x13268d
$func328 @ hes-game.wasm:0x18771
$func2036 @ hes-game.wasm:0x167054
$func341 @ hes-game.wasm:0x24a77
$func367 @ hes-game.wasm:0x3a471
$func1854 @ hes-game.wasm:0x15824f
$func1190 @ hes-game.wasm:0x103c11
$func6130 @ hes-game.wasm:0x2420ab
$func4658 @ hes-game.wasm:0x215391
$func4062 @ hes-game.wasm:0x20137e
$__wbindgen_export_6 @ hes-game.wasm:0x20bf8d
__wbg_adapter_57 @ hes-game.js:254
real @ hes-game.js:215
(anonymous) @ hes-game.js:1682
handleError @ hes-game.js:317
imports.wbg.__wbg_call_b3ca7c6051f9bec1 @ hes-game.js:1681
$func2918 @ hes-game.wasm:0x1c1637
$func498 @ hes-game.wasm:0x6be9c
$__wbindgen_export_10 @ hes-game.wasm:0x20c1aa
__wbg_adapter_73 @ hes-game.js:291
real @ hes-game.js:215
hes-game.js:1838 Uncaught RuntimeError: unreachable
    at hes-game.wasm:0x125f85
    at hes-game.wasm:0x1c434c
    at hes-game.wasm:0x216a62
    at hes-game.wasm:0x1a90ae
    at hes-game.wasm:0x24a77
    at hes-game.wasm:0x3a471
    at hes-game.wasm:0x1c9e90
    at hes-game.wasm:0x13268d
    at hes-game.wasm:0x18771
    at hes-game.wasm:0x167054
```

![image](https://github.com/user-attachments/assets/5679ebf9-41b6-41f1-b076-dd01c3400314)
Image of the above mentioned error and "empty" screen.

![image](https://github.com/user-attachments/assets/d2aaa78d-f87b-476a-b870-402f7d180f2d)
Image of the situation when adding only 9 projects.

Firefox Version 128.0.3 (64-bit):
```
panicked at alloc/src/raw_vec.rs:24:5:
capacity overflow

Stack:

__wbg_get_imports/imports.wbg.__wbg_new_abda76e883ba8a5f@https://play.half.earth/pkg/hes-game.js:629:13
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[6136]:0x242269
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1451]:0x125f61
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2974]:0x1c434c
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4721]:0x216a62
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2635]:0x1a90ae
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[341]:0x24a77
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[3052]:0x1c9e90
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1585]:0x13268d
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[328]:0x18771
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2036]:0x167054
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[341]:0x24a77
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1854]:0x15824f
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1190]:0x103c11
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[6130]:0x2420ab
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4658]:0x215391
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4062]:0x20137e
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4419]:0x20bf8d
__wbg_adapter_57@https://play.half.earth/pkg/hes-game.js:254:6
real@https://play.half.earth/pkg/hes-game.js:215:32
__wbg_get_imports/imports.wbg.__wbg_call_b3ca7c6051f9bec1/<@https://play.half.earth/pkg/hes-game.js:1682:29
handleError@https://play.half.earth/pkg/hes-game.js:317:38
__wbg_get_imports/imports.wbg.__wbg_call_b3ca7c6051f9bec1@https://play.half.earth/pkg/hes-game.js:1681:63
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2918]:0x1c1637
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[498]:0x6be9c
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4431]:0x20c1aa
__wbg_adapter_73@https://play.half.earth/pkg/hes-game.js:291:6
real@https://play.half.earth/pkg/hes-game.js:215:32
EventListener.handleEvent*__wbg_get_imports/imports.wbg.__wbg_addEventListener_53b787075bd5e003/<@https://play.half.earth/pkg/hes-game.js:946:17
handleError@https://play.half.earth/pkg/hes-game.js:317:38
__wbg_get_imports/imports.wbg.__wbg_addEventListener_53b787075bd5e003@https://play.half.earth/pkg/hes-game.js:944:75
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2764]:0x1af59f
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2312]:0x1836c2
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1752]:0x14cbe6
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1164]:0x10162d
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2036]:0x167054
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[341]:0x24a77
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[3052]:0x1c9e90
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1585]:0x13268d
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2484]:0x19ad9a
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2036]:0x167054
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[341]:0x24a77
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[3052]:0x1c9e90
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1585]:0x13268d
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1052]:0xf3d71
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2036]:0x167054
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[341]:0x24a77
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1854]:0x15824f
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[862]:0xc293b
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[954]:0xdad34
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4433]:0x20c1f0
__wbg_adapter_79@https://play.half.earth/pkg/hes-game.js:299:6
real@https://play.half.earth/pkg/hes-game.js:215:32
VoidFunction*__wbg_get_imports/imports.wbg.__wbg_queueMicrotask_481971b0d87f3dd4@https://play.half.earth/pkg/hes-game.js:1539:15
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2821]:0x1b46f4
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1882]:0x15a74f
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1006]:0xee1fe
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2984]:0x1c47b7
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4287]:0x207f59
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4166]:0x2026aa
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[3296]:0x1d4256
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[842]:0xbf797
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1832]:0x154455
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[3170]:0x1cf75b
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[3930]:0x1fe57c
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[341]:0x24a77
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[367]:0x3a471
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[3052]:0x1c9e90
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[1585]:0x13268d
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[2403]:0x197273
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[4270]:0x2066a1
@https://play.half.earth/pkg/hes-game.wasm:wasm-function[6184]:0x245df6
hydrate@https://play.half.earth/pkg/hes-game.js:312:6
@https://play.half.earth/:20:86
promise callback*@https://play.half.earth/:20:71
promise callback*@https://play.half.earth/:19:34
requestIdleCallback handler*idle@https://play.half.earth/:12:40
@https://play.half.earth/:17:29


[hes-game.js:642:9](https://play.half.earth/pkg/hes-game.js)
Uncaught RuntimeError: unreachable executed
    __wbg_adapter_57 https://play.half.earth/pkg/hes-game.js:254
    real https://play.half.earth/pkg/hes-game.js:215
    __wbg_call_b3ca7c6051f9bec1 https://play.half.earth/pkg/hes-game.js:1682
    handleError https://play.half.earth/pkg/hes-game.js:317
    __wbg_call_b3ca7c6051f9bec1 https://play.half.earth/pkg/hes-game.js:1681
    __wbg_adapter_73 https://play.half.earth/pkg/hes-game.js:291
    real https://play.half.earth/pkg/hes-game.js:215
    __wbg_addEventListener_53b787075bd5e003 https://play.half.earth/pkg/hes-game.js:946
    handleError https://play.half.earth/pkg/hes-game.js:317
    __wbg_addEventListener_53b787075bd5e003 https://play.half.earth/pkg/hes-game.js:944
    __wbg_adapter_79 https://play.half.earth/pkg/hes-game.js:299
    real https://play.half.earth/pkg/hes-game.js:215
    __wbg_queueMicrotask_481971b0d87f3dd4 https://play.half.earth/pkg/hes-game.js:1539
    hydrate https://play.half.earth/pkg/hes-game.js:312
    <anonymous> https://play.half.earth/:20
    promise callback* https://play.half.earth/:20
    promise callback* https://play.half.earth/:19
    requestIdleCallback handler*idle https://play.half.earth/:12
    <anonymous> https://play.half.earth/:17
```

![image](https://github.com/user-attachments/assets/5d3ecea3-63e4-4221-b797-8670e96f33dc)
Image of the error on Firefox.

**Comment by frnsys** [comment]
Hi, thank you for your detailed bug report. It just took a look and it's an easy fix, I'll have a fix up shortly.

**Comment by frnsys** [comment]
Ok the update's live now, you may need to force-refresh to ensure you have the latest version. Let me know if it's still not working.

**Comment by sgitkene** [comment]
Wow that was quick, thanks!
